# Generated by Django 3.0.8 on 2020-07-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='номер телефона'),
        ),
    ]
