# Generated by Django 3.0.8 on 2020-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200714_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone',
            field=models.CharField(default='', max_length=12, unique=True, verbose_name='номер телефона'),
        ),
    ]
