# Generated by Django 3.0.8 on 2020-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='стоимость акции'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='стоимость посещения'),
        ),
    ]
