# Generated by Django 3.0.8 on 2020-07-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20200720_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='время посещения'),
        ),
    ]
