# Generated by Django 3.0.8 on 2020-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='описание товара'),
        ),
    ]
