# Generated by Django 3.0.8 on 2020-07-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time',
            field=models.CharField(default='', max_length=32, verbose_name='время посещения'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='дата посещения'),
        ),
    ]
