# Generated by Django 3.0.8 on 2020-07-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200729_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('date', 'time')},
        ),
    ]
