# Generated by Django 3.0.8 on 2020-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20200729_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60, verbose_name='bot_token')),
                ('chat_id', models.CharField(max_length=20, verbose_name='chat_id')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/product_img/'),
        ),
    ]
