# Generated by Django 3.0.8 on 2020-08-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20200809_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, verbose_name='Заголовок')),
                ('text', models.TextField(default='', max_length=100000, verbose_name='Текст статьи')),
                ('image', models.ImageField(blank=True, upload_to='static/article_img/')),
            ],
        ),
    ]
