# Generated by Django 3.0.8 on 2020-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20200810_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=64, unique=True, verbose_name='Заголовок'),
        ),
    ]
