# Generated by Django 3.0.8 on 2020-08-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20200810_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageforarticle',
            name='number_in_article',
            field=models.PositiveIntegerField(default=1, verbose_name='порядковый номер в статье'),
        ),
    ]
