# Generated by Django 3.0.8 on 2020-08-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20200810_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='father_name',
            field=models.CharField(default='', max_length=64, verbose_name='отчество'),
        ),
    ]
