# Generated by Django 3.0.8 on 2020-08-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20200811_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='months',
            name='name',
        ),
        migrations.AddField(
            model_name='months',
            name='month_number',
            field=models.IntegerField(db_index=True, default=0, unique=True, verbose_name='номер месяца'),
        ),
    ]
