# Generated by Django 3.0.8 on 2020-08-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20200811_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageforarticle',
            name='article',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Article'),
        ),
    ]
