# Generated by Django 3.0.8 on 2020-08-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20200816_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
