# Generated by Django 3.0.8 on 2020-08-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20200818_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcompilation',
            name='price',
            field=models.IntegerField(default=0, verbose_name='стоимость подборки'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
