# Generated by Django 3.0.8 on 2020-08-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20200821_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='электронная почта'),
        ),
    ]
