# Generated by Django 3.0.8 on 2020-08-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20200821_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='описание товара'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='email'),
        ),
    ]
