# Generated by Django 3.0.8 on 2020-08-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20200822_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=800, verbose_name='описание товара'),
        ),
    ]
