# Generated by Django 3.0.8 on 2020-08-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20200820_1254'),
        ('orderapp', '0003_auto_20200718_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemProductCompilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('compilation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCompilation', verbose_name='подборка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items_compilations', to='orderapp.Order')),
            ],
        ),
    ]
