# Generated by Django 3.0.8 on 2020-08-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_orderitemproductcompilation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItemProductCompilation',
        ),
    ]
